work around a problem with Microsoft.SourceLink.Common.GenerateSourceLinkFile task deleting the generated sourcelink file
Since SourceLink is enabled by default in .NET8, the default GenerateSourceLinkFile task always runs, and if it doesn't generate any output, but the sourcelink file exists on disk, it deletes it: https://github.com/dotnet/sourcelink/blob/8.0.0/src/SourceLink.Common/GenerateSourceLinkFile.cs#L123. This causes a build failures like this: CSC : error CS0016: Could not write to output file '\path\to\YourProject.sourcelink.json' -- 'Could not find file '\path\to\YourProject.sourcelink.json'.'

Work around it by using a more specific sourcelink file name that is unlikely to clash with the default one and won't be deleted.